name = "xuezhi-tan-scholar-api"
main = "src/index.js"
compatibility_date = "2026-07-29"
workers_dev = true

[triggers]
crons = ["17 4 * * *"]

[[kv_namespaces]]
binding = "SCHOLAR_CACHE"
id = "608443fce0db44be86cc98aeb266afa8"
